### By default, the scripts will look for this file as one of:
###  * /etc/quotanotify/config.yaml
###  * /etc/quotanotify.yaml
###  * config.yaml  (In the same directory as the script.)
###
### You can explicitly give another location with the --config command line
### option.

### We'll document the default values for things here.  All non-absolute paths
### are considered to be relative to the location of the configuration file.

## Where the quota cache file lives.  Defaults to a file named "cache" in the
## same directory as the config file.
#cache: cache

## The SMTP server used to send mail.
#smtp_host: localhost

## The email address to send email from.
#from_address: root

## If replies to the notification emails should go somewhere other than to the
## sender, specify that here.  (The default is an empty value and signifies
## that no Reply-To: header should be used.)
#reply_to: 

## The domain name that should be attached to usernames to turn them into email
## addresses.  e.g. if domain is "example.com" and the person with username
## "foo" is over quota, email will be sent to "foo@example.com".
##
## If "from_address", above, is not a complete email address, the domain will be
## appended to it, too.
##
## The default is the FQDN of the host where the script is running.
#domain: example.com

## How long we should wait, in minutes, between someone going under quota and
## the notification email being sent.  Setting this too short could result in
## someone being inundated with emails if they rapidly add and delete data in a
## way that causes them to repeatedly exceed and then go back under their quota.
## Setting it too long can result in a long delay between someone fixing their
## quota and then getting the confirmation email.
#notification_hysteresis: 30

### Email templates.

## See the README for a description of the template values.
## The settings below should be generic enough for most cases.

templates:
  soft_limit:
    subject: Your account is over quota.
    main_file: templates/over_quota.example.jj
    block_summary_new:
      Your account ({{ai.username}}) is currently over the limit set
      for disk space used in the {{ai.filesystem}} filesystem
      (a.k.a. you are over quota).
    block_summary_old:
      Your account ({{ai.username}}) is still over its quota for disk
      space used in the {{ai.filename}} filesystem.
    inode_summary_new:
      Your account ({{ai.username}}) is currently over the limit set
      for number of files in the {{ai.filesystem}} filesystem
      (a.k.a. you are over quota).
    inode_summary_old:
      Your account ({{ai.username}}) is still over its quota for
      number of files in the {{ai.filesystem}} filesystem.
    block_detail:
      You are currently using {{ai.bytes_used|filesizeformat(True)}}
      of data in the {{ai.filesystem}} filesystem.  Your quota is
      {{ai.bytes_quota|filesizeformat(True)}}.  You should clear out
      some of your data to reduce your usage below your limit.
    inode_detail:
      You currently have {{ai.inodes_used}} files in the
      {{ai.filesystem}} filesystem.  Your limit is {{ai.inode_quota}}
      files.  You should delete some of your files to reduce your
      usage below your limit.

  hard_limit:
    subject: Your account is out of space.
    main_file: templates/over_quota.example.jj
    block_summary_new:
      Your account ({{ai.username}}) has reached its maximum allowed
      limit for disk space usage in the {{ai.filesystem}} filesystem
      (a.k.a. you have hit your quota hard limit).
    block_summary_old:
      Your account ({{ai.username}}) is still at its hard limit for
      disk space usage in the {{ai.filesystem}} filesystem.
    inode_summary_new:
      Your account ({{ai.username}}) has reached its maximum allowed
      limit for number of files in the {{ai.filesystem}} filesystem
      (a.k.a. you have hit your quota hard limit).
    inode_summary_old:
      Your account ({{ai.username}}) is still at its hard limit for
      number of files in the {{ai.filesystem}} filesystem.
    block_detail:
      You are currently using {{ai.bytes_used|filesizeformat(True)}}
      of data in the {{ai.filesystem}} filesystem.  Your quota is
      {{ai.bytes_quota|filesizeformat(True)}}.  You need to clear out
      some of your data to reduce your usage below your limit.  You
      will not be able to create any new files or make any existing
      files larger until you go back below your quota.
    inode_detail:
      You currently have {{ai.inodes_used}} files in the
      {{ai.filesystem}} filesystem.  Your limit is {{ai.inode_quota}}
      files.  You need to delete some of your files to reduce your
      usage below your limit.  You will not be able to create any new
      files until you go back below your quota.

  grace_expired:
    subject: Your account is out of space.
    main_file: templates/over_quota.example.jj
    block_summary_new:
      Your account ({{ai.username}}) has spent too much time over its
      limit for disk space usage in the {{ai.filesystem}} filesystem
      (a.k.a. you have exceeded your quota grace period).
    block_summary_old:
      Your account ({{ai.username}}) is still past its quota grace
      period for disk space usage in the {{ai.filesystem}} filesystem.
    inode_summary_new:
      Your account ({{ai.username}}) has spent too much time over its
      limit for number of files in the {{ai.filesystem}} filesystem
      (a.k.a. you have exceeded your quota grace period).
    inode_summary_old:
      Your account ({{ai.username}}) is still past its quota grace
      period for number of files in the {{ai.filesystem}} filesystem.
    block_detail:
      You are currently using {{ai.bytes_used|filesizeformat(True)}}
      of data in the {{ai.filesystem}} filesystem.  Your quota is
      {{ai.bytes_quota|filesizeformat(True)}}.  You need to clear out
      some of your data to reduce your usage below your limit.  You
      will not be able to create any new files or make any existing
      files larger until you go back below your quota.
    inode_detail:
      You currently have {{ai.inodes_used}} files in the
      {{ai.filesystem}} filesystem.  Your limit is {{ai.inode_quota}}
      files.  You need to delete some of your files to reduce your
      usage below your limit.  You will not be able to create any new
      files until you go back below your quota.

  under_quota:
    subject: Your account is back under quota.
    main_file: templates/under_quota.example.jj
    block_summary_new:
    block_summary_old:
    inode_summary_new:
    inode_summary_old:
    block_detail:
      For reference, you are currently using
      {{ai.bytes_used|filesizeformat(True)}} of data in the
      {{ai.filesystem}} filesystem and your quota is
      {{ai.bytes_quota|filesizeformat(True)}}.
    inode_detail:
      For reference, you currently have {{ai.inodes_used}} files in
      the {{ai.filesystem}} filesystem and your quota is
      {{ai.inode_quota}} files.
